### ISSUE TITLE
Blacklist feature

### ISSUE THREAD

**Issue by rayman89** [Reeywhaar/holdtab#2]
Could you consider if possible adding a blacklist feature (aka load on select only happens on those pages) because it's useful for the kind of pages you mention in the description but on normal browsing it can be bothersome sometimes.

**Comment by reeywhaar** [comment]
Dear @rayman89, thank you for report!
I have added the feature you were requesting. Right now it in beta phase, because I think I need to test it for a while. You can test it as well by installing extension from developer channel at https://addons.mozilla.org/en-US/firefox/addon/holdtab/versions/beta?page=1#version-0.0.10pre2

Thank you!

**Comment by rayman89** [comment]
I tested and works properly but the tab on the background appears as loading indefinitely and not as "not loaded" is that expected?

**Comment by reeywhaar** [comment]
Yes, spinning wheel is literally "by design". I was trying to get rid of it, by redirecting to proxy-page, but it adds unnecessary overload.

**Comment by rayman89** [comment]
The problem with that is that is if the tab is never loaded when the browser is closed and the session restored those tabs are all about:blank.

**Comment by reeywhaar** [comment]
@rayman89, that's a really good bug report. I haven't thought of such situation and it should be corrected, if possible. I will investigate. Thank you!
